### ISSUE TITLE
"the ReLU activation function is followed by W0" Mentioned in your paper is different from your code?

### ISSUE THREAD

**Issue by getr1ch** [Jongchan/attention-module#40]
According to the following code,the W0 is followed by the ReLU activation function? or I misunderstood,cause i'm new to DeepLearning，plz pardon me.
`
self.mlp = nn.Sequential(
            Flatten(),
            nn.Linear(gate_channels, gate_channels // reduction_ratio), #W0 ?
            nn.ReLU(),
            nn.Linear(gate_channels // reduction_ratio, gate_channels)  #W1 ?
            )
`

**Comment by getr1ch** [comment]
`self.mlp = nn.Sequential(`
`    Flatten(),`
`    nn.Linear(gate_channels, gate_channels // reduction_ratio),`
`    nn.Relu(),`
`    nn.Linear(gate_channels // reduction_ratio, gate_channels),`

**Comment by DyCheer** [comment]
It is necessary to add an activation function between the two layers

**Comment by getr1ch** [comment]
> It is necessary to add an activation function between the two layers

大佬，所以应该是”W0 is followed by the ReLU activation function“，对吗？

**Comment by DyCheer** [comment]
对！

**Comment by getr1ch** [comment]
> 对！

好的，谢谢大佬
